.TH "glcore::shader" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glcore::shader
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "shader_type \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBsource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBshader\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string glcore::shader::source"

.PP
Definition at line \fB34\fP of file \fBshader\&.h\fP\&.
.SS "shader_type glcore::shader::type"

.PP
Definition at line \fB33\fP of file \fBshader\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
