.TH "glcore::index_buffer" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glcore::index_buffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBindex_buffer\fP (std::uint32_t *indices, std::uint32_t count)"
.br
.ti -1c
.RI "void \fBbind\fP () const"
.br
.ti -1c
.RI "void \fBunbind\fP () const"
.br
.ti -1c
.RI "std::uint32_t \fBcount\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBindex_buffer\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "glcore::index_buffer::index_buffer (std::uint32_t * indices, std::uint32_t count)"

.PP
Definition at line \fB33\fP of file \fBindex_buffer\&.h\fP\&.
.SS "glcore::index_buffer::~index_buffer ()"

.PP
Definition at line \fB41\fP of file \fBindex_buffer\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void glcore::index_buffer::bind () const"

.PP
Definition at line \fB46\fP of file \fBindex_buffer\&.h\fP\&.
.SS "std::uint32_t glcore::index_buffer::count () const"

.PP
Definition at line \fB56\fP of file \fBindex_buffer\&.h\fP\&.
.SS "void glcore::index_buffer::unbind () const"

.PP
Definition at line \fB51\fP of file \fBindex_buffer\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
