.TH "glcore::vertex_array" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glcore::vertex_array
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbind\fP () const"
.br
.ti -1c
.RI "void \fBunbind\fP () const"
.br
.ti -1c
.RI "void \fBadd_vertex_buffer\fP (const \fBvertex_buffer\fP &vbo)"
.br
.ti -1c
.RI "void \fBset_index_buffer\fP (const \fBindex_buffer\fP &ibo)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBvertex_array\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "glcore::vertex_array::vertex_array ()"

.PP
Definition at line \fB40\fP of file \fBvertex_array\&.h\fP\&.
.SS "glcore::vertex_array::~vertex_array ()"

.PP
Definition at line \fB45\fP of file \fBvertex_array\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void glcore::vertex_array::add_vertex_buffer (const \fBvertex_buffer\fP & vbo)"

.PP
Definition at line \fB60\fP of file \fBvertex_array\&.h\fP\&.
.SS "void glcore::vertex_array::bind () const"

.PP
Definition at line \fB50\fP of file \fBvertex_array\&.h\fP\&.
.SS "void glcore::vertex_array::set_index_buffer (const \fBindex_buffer\fP & ibo)"

.PP
Definition at line \fB80\fP of file \fBvertex_array\&.h\fP\&.
.SS "void glcore::vertex_array::unbind () const"

.PP
Definition at line \fB55\fP of file \fBvertex_array\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
