.TH "include/glcore/glcore.h" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/glcore/glcore.h \- GLCore, a C++17 wrapper for OpenGL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'modules/index_buffer\&.h'\fP
.br
\fC#include 'modules/shader\&.h'\fP
.br
\fC#include 'modules/vertex_array\&.h'\fP
.br
\fC#include 'modules/vertex_buffer\&.h'\fP
.br
\fC#include 'modules/vertex_buffer_layout\&.h'\fP
.br

.SH "Detailed Description"
.PP 
GLCore, a C++17 wrapper for OpenGL\&. 


.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-28
.RE
.PP
GLCore is a C++17 wrapper for OpenGL\&. It is designed to be simple and easy to use\&. simply import this header file and provide your own OpenGL loader in \fBmodules/gl_functions\&.h\fP\&.
.PP
\fBWarning\fP
.RS 4
\fBIMPORTANT\fP Do not forget to provide an OpenGL loader in \fBmodules/gl_functions\&.h\fP, or else GLCore will not work\&.
.RE
.PP
\fBSee also\fP
.RS 4
\fBmodules/gl_functions\&.h\fP 
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License 
.RE
.PP

.PP
Definition in file \fBglcore\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
