.TH "glcore::vertex_attribute" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glcore::vertex_attribute
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "shader_data_type::type_t \fBtype\fP"
.br
.ti -1c
.RI "std::string_view \fBname\fP"
.br
.ti -1c
.RI "std::uint32_t \fBoffset\fP {}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBvertex_buffer_layout\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string_view glcore::vertex_attribute::name"

.PP
Definition at line \fB24\fP of file \fBvertex_buffer_layout\&.h\fP\&.
.SS "std::uint32_t glcore::vertex_attribute::offset {}"

.PP
Definition at line \fB25\fP of file \fBvertex_buffer_layout\&.h\fP\&.
.SS "shader_data_type::type_t glcore::vertex_attribute::type"

.PP
Definition at line \fB23\fP of file \fBvertex_buffer_layout\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
