.TH "glcore::vertex_buffer_layout" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glcore::vertex_buffer_layout
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvertex_buffer_layout\fP (std::initializer_list< \fBvertex_attribute\fP > attributes)"
.br
.ti -1c
.RI "std::uint32_t \fBstride\fP () const"
.br
.ti -1c
.RI "const std::vector< \fBvertex_attribute\fP > & \fBdata\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB28\fP of file \fBvertex_buffer_layout\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "glcore::vertex_buffer_layout::vertex_buffer_layout (std::initializer_list< \fBvertex_attribute\fP > attributes)"

.PP
Definition at line \fB41\fP of file \fBvertex_buffer_layout\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "const std::vector< \fBvertex_attribute\fP > & glcore::vertex_buffer_layout::data () const"

.PP
Definition at line \fB55\fP of file \fBvertex_buffer_layout\&.h\fP\&.
.SS "std::uint32_t glcore::vertex_buffer_layout::stride () const"

.PP
Definition at line \fB50\fP of file \fBvertex_buffer_layout\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
