.TH "glcore::vertex_buffer" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glcore::vertex_buffer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvertex_buffer\fP (float *vertices, std::uint32_t size)"
.br
.ti -1c
.RI "\fBvertex_buffer\fP (float *vertices, std::uint32_t size, const \fBvertex_buffer_layout\fP &layout)"
.br
.ti -1c
.RI "void \fBbind\fP () const"
.br
.ti -1c
.RI "void \fBunbind\fP () const"
.br
.ti -1c
.RI "void \fBset_layout\fP (const \fBvertex_buffer_layout\fP &layout)"
.br
.ti -1c
.RI "const \fBvertex_buffer_layout\fP & \fBlayout\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBvertex_buffer\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "glcore::vertex_buffer::vertex_buffer (float * vertices, std::uint32_t size)"

.PP
Definition at line \fB40\fP of file \fBvertex_buffer\&.h\fP\&.
.SS "glcore::vertex_buffer::vertex_buffer (float * vertices, std::uint32_t size, const \fBvertex_buffer_layout\fP & layout)"

.PP
Definition at line \fB47\fP of file \fBvertex_buffer\&.h\fP\&.
.SS "glcore::vertex_buffer::~vertex_buffer ()"

.PP
Definition at line \fB53\fP of file \fBvertex_buffer\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void glcore::vertex_buffer::bind () const"

.PP
Definition at line \fB58\fP of file \fBvertex_buffer\&.h\fP\&.
.SS "const \fBvertex_buffer_layout\fP & glcore::vertex_buffer::layout () const"

.PP
Definition at line \fB73\fP of file \fBvertex_buffer\&.h\fP\&.
.SS "void glcore::vertex_buffer::set_layout (const \fBvertex_buffer_layout\fP & layout)"

.PP
Definition at line \fB68\fP of file \fBvertex_buffer\&.h\fP\&.
.SS "void glcore::vertex_buffer::unbind () const"

.PP
Definition at line \fB63\fP of file \fBvertex_buffer\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
