.TH "include/glcore/modules/index_buffer.h" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/glcore/modules/index_buffer.h \- Element Buffer Object (EBO) wrapper\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gl_functions\&.h'\fP
.br
\fC#include <cstdint>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglcore::index_buffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Element Buffer Object (EBO) wrapper\&. 


.PP
\fBAuthor\fP
.RS 4
Christian Panov 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-28
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License 
.RE
.PP

.PP
Definition in file \fBindex_buffer\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
