.TH "include/glcore/modules/shader.h" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/glcore/modules/shader.h \- Shader program wrapper\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gl_functions\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglcore::shader\fP"
.br
.ti -1c
.RI "class \fBglcore::shader_program\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBshader_type\fP { \fBvertex\fP, \fBfragment\fP, \fBtess_control\fP, \fBtess_eval\fP, \fBgeometry\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Shader program wrapper\&. 


.PP
\fBAuthor\fP
.RS 4
Christian Panov 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-28
.RE
.PP
Shader program wrapper, used to load and compile shaders, also implement a very simple uniform uploading system and a simple shader parser that allows the definition of multiple shaders in a single file through the use of shader tags\&.
.PP
\fBCopyright\fP
.RS 4
MIT License 
.RE
.PP

.PP
Definition in file \fBshader\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class glcore::shader_type\fC [strong]\fP"

.PP
Definition at line \fB24\fP of file \fBshader\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
