.TH "include/glcore/modules/utility.h" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/glcore/modules/utility.h \- Utility functions for parsing files\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br

.SH "Detailed Description"
.PP 
Utility functions for parsing files\&. 


.PP
\fBAuthor\fP
.RS 4
Christian Panov 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-28
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License 
.RE
.PP

.PP
Definition in file \fButility\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
