.TH "include/glcore/modules/vertex_buffer_layout.h" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/glcore/modules/vertex_buffer_layout.h \- Vertex Buffer Layout abstraction\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string_view>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'shader_data_type\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglcore::vertex_attribute\fP"
.br
.ti -1c
.RI "class \fBglcore::vertex_buffer_layout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vertex Buffer Layout abstraction\&. 


.PP
\fBAuthor\fP
.RS 4
Christian Panov 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-28
.RE
.PP
Provides a simple abstraction for vertex buffer layouts, allowing to specify the layout of the vertex buffer in a simple and easy to use way\&.
.PP
\fBCopyright\fP
.RS 4
MIT License 
.RE
.PP

.PP
Definition in file \fBvertex_buffer_layout\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
