.TH "include/glcore/modules/vertex_array.h" 3 "Fri Apr 28 2023" "GLCore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/glcore/modules/vertex_array.h \- Vertex Array Object (VAO) wrapper\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'gl_functions\&.h'\fP
.br
\fC#include 'index_buffer\&.h'\fP
.br
\fC#include 'vertex_buffer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglcore::vertex_array\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vertex Array Object (VAO) wrapper\&. 


.PP
\fBAuthor\fP
.RS 4
Christian Panov 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-04-28
.RE
.PP
\fBCopyright\fP
.RS 4
MIT License 
.RE
.PP

.PP
Definition in file \fBvertex_array\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for GLCore from the source code\&.
